<script setup lang="ts">
import { computed } from "vue";
import {
  Home,
  FolderKanban,
  CheckSquare,
  FileText,
  Trash2,
  Plus,
  Search,
  Settings,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  X,
  Edit,
  MoreVertical,
  Calendar,
  User,
  Clock,
  Tag,
  Link,
  ArrowRight,
  ArrowLeft,
  MoreHorizontal,
  Maximize2,
  Minimize2,
  RefreshCw,
  Filter,
  SortAsc,
  Grid,
  List,
  Bell,
  Menu,
  ChevronUp,
  Star,
  StarOff,
  Copy,
  Download,
  Upload,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  AlertCircle,
  CheckCircle,
  Info,
  AlertTriangle,
  HelpCircle,
  Zap,
  Activity,
  BarChart3,
  PieChart,
  TrendingUp,
  Users,
  Building2,
  Briefcase,
  Target,
  Rocket,
  Lightbulb,
  Bookmark,
  BookmarkCheck,
  Layers,
  Package,
  Database,
  Server,
  Cloud,
  HardDrive,
  Cpu,
  Wifi,
  WifiOff,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Camera,
  Image,
  File,
  Folder,
  FilePlus,
  FolderPlus,
  FileMinus,
  FolderMinus,
  FileEdit,
  FileSearch,
  FileOutput,
  FileInput,
  Save,
  Printer,
  Scissors,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Archive,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  ArrowDownRight,
  ArrowUpLeft,
  ArrowDownLeft,
  RotateCw,
  RotateCcw,
  FlipHorizontal,
  FlipVertical,
  ZoomIn,
  ZoomOut,
  Move,
  MousePointer,
  Hand,
} from "lucide-vue-next";

const props = withDefaults(defineProps<{
  name: string;
  size?: number;
  strokeWidth?: number;
  class?: string;
}>(), {
  size: 20,
  strokeWidth: 2,
  class: "text-[var(--text-secondary)]"  // Default dark theme icon color
});

const icons: Record<string, any> = {
  home: Home,
  "folder-kanban": FolderKanban,
  "check-square": CheckSquare,
  "file-text": FileText,
  "trash-2": Trash2,
  plus: Plus,
  search: Search,
  settings: Settings,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  x: X,
  edit: Edit,
  "more-vertical": MoreVertical,
  "more-horizontal": MoreHorizontal,
  calendar: Calendar,
  user: User,
  clock: Clock,
  tag: Tag,
  link: Link,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "arrow-up-right": ArrowUpRight,
  "arrow-down-right": ArrowDownRight,
  "arrow-up-left": ArrowUpLeft,
  "arrow-down-left": ArrowDownLeft,
  "rotate-cw": RotateCw,
  "rotate-ccw": RotateCcw,
  "flip-horizontal": FlipHorizontal,
  "flip-vertical": FlipVertical,
  "maximize-2": Maximize2,
  "minimize-2": Minimize2,
  "refresh-cw": RefreshCw,
  filter: Filter,
  "sort-asc": SortAsc,
  grid: Grid,
  list: List,
  bell: Bell,
  menu: Menu,
  star: Star,
  "star-off": StarOff,
  copy: Copy,
  download: Download,
  upload: Upload,
  eye: Eye,
  "eye-off": EyeOff,
  lock: Lock,
  unlock: Unlock,
  "alert-circle": AlertCircle,
  "check-circle": CheckCircle,
  info: Info,
  warning: AlertTriangle,
  "help-circle": HelpCircle,
  zap: Zap,
  activity: Activity,
  "bar-chart-3": BarChart3,
  "pie-chart": PieChart,
  "trending-up": TrendingUp,
  users: Users,
  "building-2": Building2,
  briefcase: Briefcase,
  target: Target,
  rocket: Rocket,
  "lightbulb": Lightbulb,
  bookmark: Bookmark,
  "bookmark-check": BookmarkCheck,
  layers: Layers,
  package: Package,
  database: Database,
  server: Server,
  cloud: Cloud,
  "hard-drive": HardDrive,
  cpu: Cpu,
  wifi: Wifi,
  "wifi-off": WifiOff,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  mic: Mic,
  "mic-off": MicOff,
  camera: Camera,
  image: Image,
  file: File,
  folder: Folder,
  "file-plus": FilePlus,
  "folder-plus": FolderPlus,
  "file-minus": FileMinus,
  "folder-minus": FolderMinus,
  "file-edit": FileEdit,
  "file-search": FileSearch,
  "file-output": FileOutput,
  "file-input": FileInput,
  save: Save,
  printer: Printer,
  scissors: Scissors,
  clipboard: Clipboard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  archive: Archive,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  move: Move,
  "mouse-pointer": MousePointer,
  hand: Hand,
};

const iconComponent = computed(() => icons[props.name] || HelpCircle);
</script>

<template>
  <component
    :is="iconComponent"
    :size="size || 20"
    :stroke-width="strokeWidth || 2"
    :class="props.class"
  />
</template>
